# Site Settings
#title           : "IXEnv Blog"
title           : "The Source"
author          : "Daniel Filonik"
description     : "Interaction Environments"
locale          : "en-AU"
theme           : jekyll-theme-minimal

# Github metadata settings
github: [metadata]
repository: filonik/filonik.github.io

# Gem settings
gems:
  - jekyll-github-metadata
  - jemoji


